project:
  type: website
  output-dir: docs

website:
  google-analytics:
    tracking-id: "G-XYECR0MZCR"
  title: "Marco Bravo"
  favicon: "images/favicon.jpg"
  search: 
    location: navbar
    type: textbox
  page-footer:
    center: |
      [Contact Marco Bravo](mailto:marcop.bravom@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Github Code Repo](https://github.com/Marcony1/marcony1.github.io)
    background: "#2d3e50"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd
      - text: Posts
        href: posts.qmd
      - text: Talks
        href: talks.qmd
        
    right:
      - icon: github
        href: https://github.com/Marcony1
      - icon: linkedin
        href: https://www.linkedin.com/in/marco-bravom/
      - icon: envelope
        href: mailto:marcop.bravom@gmail.com
     

format:
  html:
    theme: 
      light: flatly
      dark: [flatly, theme_dark_custom.scss]
    code-link: true
    code-fold: show
    highlight-style: github
    mainfont: arial
    fontsize: 1.5rem
    monofont: courier new
    css: styles.css
    toc: true
    grid: 
      body-width: 1000px


execute:
  freeze: auto
  
