project:
  type: website
  output-dir: docs

website:
  title: "Marco Bravo"
  search: 
    location: navbar
    type: textbox
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd
        
    right:
      - icon: github
        href: https://github.com/Marcony1
      - icon: linkedin
        href: https://www.linkedin.com/in/marco-bravom/
      - icon: envelope
        href: mailto:marcop.bravom@gmail.com
     

format:
  html:
    theme: 
      light: flatly
      dark: [flatly, theme_dark_custom.scss]
    code-link: true
    mainfont: arial
    fontsize: 1.5rem
    monofont: courier new
    css: styles.css
    toc: true


execute:
  freeze: auto
