project:
  type: website
  output-dir: docs

website:
  title: "Marco Bravo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd

format:
  html:
    theme: flatly
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#333333"
    linkcolor: "#0056b3"
    monofont: courier new
    css: styles.css
    toc: true


execute:
  freeze: auto
